---
# tasks file for app

# Prerequisites
- name: update apt
  apt: update_cache=yes



#Docker Task

# Install prerequisite packages

- name: Install prerequisite packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

# Add Docker GPG key
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add Docker APT repository
- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

# Install Docker
- name: Install Docker
  apt:
    name: docker-ce
    state: present

# Add current user to Docker group
- name: Add current user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

# Configure Docker to run without sudo
- name: Configure Docker to run without sudo
  copy:
    content: |
      {
        "userns-remap": "default"
      }
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: Restart Docker

  handlers:
  # Restart Docker service
  - name: Restart Docker
    systemd:
      name: docker
      state: restarted




#Jenkins Task

- name: Install Java
  apt:
    name: openjdk-8-jdk
    state: present

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

#AWS CLI 

- name: Install Python pip
  apt:
    name: python-pip
    state: present

- name: Install AWS CLI using pip
  pip:
    name: awscli
    state: present


# kubeconfig for eks
- name: Update kubeconfig for EKS cluster
  shell: aws eks --region "us-east-1" update-kubeconfig --name demo

# add ingress nginx controller 

- name: Add ingress nginx
  shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

# install ingress controller 

- name: Install ingress nginx
  shell: helm install ingress-nginx ingress-nginx/ingress-nginx